---
deployment:
  tasks:
    - export DEPLOYPATH=/home/negeobag/himawat
    - /bin/cp -R accounts $DEPLOYPATH
    - /bin/cp -R dashboard $DEPLOYPATH
    - /bin/cp -R himwat $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R services $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R media $DEPLOYPATH
    - /bin/cp -R tmp $DEPLOYPATH
    - /bin/cp manage.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH/.env
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - bin/cp package-lock.json $DEPLOYPATH
    - bin/cp -R node_modules $DEPLOYPATH
