# Generated by Django 4.2.29 on 2026-03-16 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Friendly name for this configuration', max_length=255)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI (GPT-4, GPT-3.5)'), ('anthropic', 'Anthropic (Claude)'), ('cohere', 'Cohere'), ('custom', 'Custom API')], default='openai', max_length=20)),
                ('api_key', models.CharField(help_text='API key for the service', max_length=500)),
                ('api_endpoint', models.URLField(blank=True, help_text='Custom API endpoint (for custom provider)')),
                ('model', models.CharField(default='gpt-3.5-turbo', help_text='Model name (e.g., gpt-4, claude-3-sonnet)', max_length=100)),
                ('system_prompt', models.TextField(blank=True, help_text='System prompt to guide AI behavior')),
                ('max_tokens', models.PositiveIntegerField(default=1000, help_text='Maximum tokens for generation')),
                ('temperature', models.FloatField(default=0.7, help_text='Creativity (0.0-1.0)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Set as default configuration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('revision_reason', models.TextField(blank=True, help_text='Why was this revision created?')),
                ('is_auto_save', models.BooleanField(default=False, help_text='True for auto-saves, False for manual saves')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_revisions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dashboard.post')),
            ],
            options={
                'verbose_name': 'Post Revision',
                'verbose_name_plural': 'Post Revisions',
                'ordering': ['-revision_number', '-created_at'],
                'unique_together': {('post', 'revision_number')},
            },
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('template', models.CharField(blank=True, max_length=50)),
                ('blocks', models.JSONField(blank=True, null=True)),
                ('revision_reason', models.TextField(blank=True, help_text='Why was this revision created?')),
                ('is_auto_save', models.BooleanField(default=False, help_text='True for auto-saves, False for manual saves')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_revisions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dashboard.page')),
            ],
            options={
                'verbose_name': 'Page Revision',
                'verbose_name_plural': 'Page Revisions',
                'ordering': ['-revision_number', '-created_at'],
                'unique_together': {('page', 'revision_number')},
            },
        ),
    ]
