# Generated by Django 4.2.29 on 2026-03-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_aiconfiguration_postrevision_pagerevision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='provider',
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='api_key',
            field=models.CharField(help_text='DeepSeek API key', max_length=500),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='max_tokens',
            field=models.PositiveIntegerField(default=2000, help_text='Maximum tokens for generation'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='model',
            field=models.CharField(choices=[('deepseek-chat', 'DeepSeek Chat'), ('deepseek-coder', 'DeepSeek Coder')], default='deepseek-chat', help_text='DeepSeek model to use', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='Creativity (0.0-2.0)'),
        ),
    ]
