# Generated by Django 4.2.29 on 2026-03-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_aiconfiguration_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconfiguration',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Configuration', 'verbose_name_plural': 'AI Configurations'},
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='max_tokens',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='model',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='status',
        ),
        migrations.RemoveField(
            model_name='aiconfiguration',
            name='temperature',
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='api_endpoint',
            field=models.CharField(default='https://api.z.ai/api/paas/v4/', help_text='API endpoint URL', max_length=500),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='model_name',
            field=models.CharField(default='glm-4.5', help_text='Model name (e.g., glm-4.5, deepseek-chat, gpt-4)', max_length=100),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='api_key',
            field=models.CharField(help_text='API key', max_length=500),
        ),
    ]
