# Generated by Django 4.2.29 on 2026-03-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_simplify_ai_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='template_name',
            field=models.CharField(blank=True, help_text="Custom template path (e.g., 'cms/categories/services-category.html'). Leave empty for auto-detection.", max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='template_name',
            field=models.CharField(blank=True, help_text="Custom template path (e.g., 'cms/pages/services-page.html'). Overrides preset template if specified.", max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='template_name',
            field=models.CharField(blank=True, help_text="Custom template path (e.g., 'cms/posts/services-post.html'). Leave empty for auto-detection.", max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('full_width', 'Full Width')], default='default', help_text='Preset template or leave empty for custom template', max_length=50),
        ),
    ]
