# Generated by Django 4.2.29 on 2026-03-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_category_template_name_page_template_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-home', 'fas fa-user')", max_length=100),
        ),
    ]
