# Generated by Django 4.2.29 on 2026-03-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_service_training_trainingrequest_trainingimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrequest',
            name='training',
        ),
        migrations.DeleteModel(
            name='TrainingRequest',
        ),
        migrations.DeleteModel(
            name='TrainingImage',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
