# Generated by Django 4.2.29 on 2026-03-20 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_training_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
