# Generated by Django 4.2.29 on 2026-03-20 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_remove_service_image_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary for listing pages')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainings/')),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-graduation-cap')", max_length=100)),
                ('category', models.CharField(choices=[('vastu_training', 'Vastu Training'), ('engineering_training', 'Engineering Training'), ('mason_training', 'Mason Training'), ('construction_training', 'Construction Training'), ('interior_design', 'Interior Design'), ('other', 'Other')], default='vastu_training', max_length=25)),
                ('duration', models.CharField(blank=True, help_text="e.g., '5 days', '2 weeks'", max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Training fee or leave empty', max_digits=10, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-featured', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='dashboard.training')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
