# Generated by Django 4.2.29 on 2026-03-20 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0010_training_trainingrequest'),
    ]

    operations = [
        # Add applies_to field to Category
        migrations.AddField(
            model_name='category',
            name='applies_to',
            field=models.ManyToManyField(blank=True, help_text='Select which content types this category applies to', limit_choices_to={'model__in': ['post', 'page', 'service', 'training']}, related_name='categories', to='contenttypes.contenttype'),
        ),
        # Add category field to Page
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='dashboard.category'),
        ),
    ]
