# Generated by Django 4.2.29 on 2026-03-20 15:05

from django.db import migrations, models
import django.db.models.deletion


def create_categories_and_migrate_data(apps, schema_editor):
    """Create Category objects and migrate old string categories to foreign keys"""
    Category = apps.get_model('dashboard', 'Category')
    Product = apps.get_model('dashboard', 'Product')
    Service = apps.get_model('dashboard', 'Service')
    Training = apps.get_model('dashboard', 'Training')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Define old categories to create
    product_categories = [
        ('Vastu Remedy', 'vastu-remedy'),
        ('Vastu Product', 'vastu-product'),
        ('Book', 'book'),
        ('Consultation', 'consultation'),
    ]

    service_categories = [
        ('Vastu Consultation', 'vastu-consultation'),
        ('Site Planning', 'site-planning'),
        ('Building Design', 'building-design'),
        ('Construction', 'construction'),
        ('Interior Design', 'interior-design'),
        ('Renovation', 'renovation'),
    ]

    training_categories = [
        ('Vastu Training', 'vastu-training'),
        ('Engineering Training', 'engineering-training'),
        ('Mason Training', 'mason-training'),
        ('Construction Training', 'construction-training'),
        ('Interior Design', 'interior-design'),
        ('Other', 'other'),
    ]

    # Create product categories
    product_ct = ContentType.objects.get_for_model(Product)
    for name, slug in product_categories:
        cat, created = Category.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'status': 'active'}
        )
        if created:
            cat.applies_to.add(product_ct)

    # Create service categories
    service_ct = ContentType.objects.get_for_model(Service)
    for name, slug in service_categories:
        cat, created = Category.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'status': 'active'}
        )
        if created:
            cat.applies_to.add(service_ct)

    # Create training categories
    training_ct = ContentType.objects.get_for_model(Training)
    for name, slug in training_categories:
        cat, created = Category.objects.get_or_create(
            slug=slug,
            defaults={'name': name, 'status': 'active'}
        )
        if created:
            cat.applies_to.add(training_ct)

    # Map old string values to new Category slugs
    category_mapping = {
        # Products
        'vastu_remedy': 'vastu-remedy',
        'vastu_product': 'vastu-product',
        'book': 'book',
        'consultation': 'consultation',
        # Services
        'vastu_consultation': 'vastu-consultation',
        'site_planning': 'site-planning',
        'building_design': 'building-design',
        'construction': 'construction',
        'interior_design': 'interior-design',
        'renovation': 'renovation',
        # Trainings
        'vastu_training': 'vastu-training',
        'engineering_training': 'engineering-training',
        'mason_training': 'mason-training',
        'construction_training': 'construction-training',
    }

    # Update Products using raw SQL to store category IDs temporarily
    for old_value, new_slug in category_mapping.items():
        try:
            new_cat = Category.objects.get(slug=new_slug)
            # Update all products with this old category to the new category ID (as string for now)
            Product.objects.filter(category=old_value).update(category=str(new_cat.pk))
        except Category.DoesNotExist:
            pass

    # Update Services using raw SQL
    for old_value, new_slug in category_mapping.items():
        try:
            new_cat = Category.objects.get(slug=new_slug)
            Service.objects.filter(category=old_value).update(category=str(new_cat.pk))
        except Category.DoesNotExist:
            pass

    # Update Trainings using raw SQL
    for old_value, new_slug in category_mapping.items():
        try:
            new_cat = Category.objects.get(slug=new_slug)
            Training.objects.filter(category=old_value).update(category=str(new_cat.pk))
        except Category.DoesNotExist:
            pass

    # Clear remaining non-numeric categories
    Product.objects.exclude(category__regex=r'^\d+$').update(category=None)
    Service.objects.exclude(category__regex=r'^\d+$').update(category=None)
    Training.objects.exclude(category__regex=r'^\d+$').update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_category_applies_to_page_category_and_more'),
    ]

    operations = [
        # First create categories and migrate data
        migrations.RunPython(create_categories_and_migrate_data),
        # Then alter the fields
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='dashboard.category'),
        ),
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='dashboard.category'),
        ),
    ]
