# Generated by Django 4.2.29 on 2026-03-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_convert_product_service_training_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Brief summary for listing pages'),
        ),
    ]
