# Generated by Django 4.2.29 on 2026-03-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_service_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Email Configuration', help_text='Friendly name for this configuration', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Use this configuration as the default')),
                ('backend', models.CharField(choices=[('console', 'Console (Development)'), ('smtp', 'SMTP (Production)')], default='console', help_text='Email backend to use', max_length=20)),
                ('email_host', models.CharField(blank=True, default='smtp.gmail.com', help_text='SMTP server hostname', max_length=255)),
                ('email_port', models.IntegerField(default=587, help_text='SMTP server port')),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS for encryption')),
                ('email_host_user', models.EmailField(blank=True, default='', help_text='SMTP username (usually email address)', max_length=254)),
                ('email_host_password', models.CharField(blank=True, default='', help_text='SMTP password or app password', max_length=255)),
                ('from_email', models.EmailField(blank=True, default='noreply@localhost', help_text='Default from email address', max_length=254)),
                ('from_name', models.CharField(blank=True, default='Himwatkhanda Vastu', help_text='Sender display name', max_length=255)),
                ('admin_email', models.EmailField(blank=True, default='admin@localhost', help_text='Admin email for notifications', max_length=254)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this configuration')),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
