# Generated by Django 4.2.29 on 2026-03-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_emailconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='anthem',
            field=models.FileField(blank=True, help_text='Company anthem MP3 file', null=True, upload_to='company/anthem/'),
        ),
    ]
