# Generated by Django 4.2.29 on 2026-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_companyinfo_anthem'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
