# Generated by Django 4.2.29 on 2026-03-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_consultation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='service_type',
            field=models.CharField(blank=True, help_text='Comma-separated: onsite, online', max_length=50),
        ),
    ]
