# Generated by Django 5.2.12 on 2026-03-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_contact_alter_category_applies_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4, WebM, etc.)', null=True, upload_to='testimonials/videos/'),
        ),
    ]
