# Generated by Django 4.2.30 on 2026-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_companyinfo_google_analytics_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='keywords',
            new_name='meta_keywords',
        ),
        migrations.AddField(
            model_name='download',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='download',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='download',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
