# Generated by Django 4.2.30 on 2026-04-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_add_seo_fields_to_post_and_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='google_search_console_id',
            field=models.CharField(blank=True, help_text='Google Search Console verification meta tag content value (e.g., abc123XYZ)', max_length=255),
        ),
    ]
