# Generated by Django 4.2.30 on 2026-04-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_add_google_search_console_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Default meta keywords for all pages (can be overridden per page)'),
        ),
        migrations.AlterField(
            model_name='download',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagerevision',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='meta_keywords',
            field=models.TextField(blank=True),
        ),
    ]
