# Generated by Django 4.2.29 on 2026-03-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CEO Name', max_length=255)),
                ('title', models.CharField(blank=True, default='Founder & CEO', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Short biography of the CEO')),
                ('message', models.TextField(blank=True, help_text='Welcome message from CEO')),
                ('photo', models.ImageField(blank=True, help_text='CEO Photo (recommended: 400x400px)', null=True, upload_to='ceo/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('social_linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('social_twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('social_facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('is_active', models.BooleanField(default=True, help_text='Display CEO info on frontend')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CEO Info',
                'verbose_name_plural': 'CEO Info',
            },
        ),
        migrations.CreateModel(
            name='ConsultationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='consultations/files/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, help_text='Specific requirements for this item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='cms.product')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='productrequest',
            name='product',
        ),
        migrations.AddField(
            model_name='consultation',
            name='captcha_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='captcha_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AddField(
            model_name='productrequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.productrequest'),
        ),
        migrations.AddField(
            model_name='consultationfile',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cms.consultation'),
        ),
        migrations.AlterUniqueTogether(
            name='productrequestitem',
            unique_together={('request', 'product')},
        ),
    ]
